name: 自动扫描并测速直播源

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检查并下载仓库代码
      uses: actions/checkout@v4

    - name: 配置 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 在服务器安装谷歌浏览器 (Selenium必备)
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: 安装全部核心依赖与爬虫组件
      run: |
        python -m pip install --upgrade pip
        pip install requests[socks] futures selenium

    - name: 执行抓取与合并脚本
      run: |
        python itv_all.py || python a.py

    - name: 自动把新文件提交存回仓库
      run: |
        git config --global user.name "actions-user"
        git config --global user.email "action@github.com"
        git add .
        git commit -m "自动更新直播源成功" || exit 0
        git push
